### ISSUE TITLE
libusb now libusb1

### ISSUE THREAD

**Issue by adam-burns** [johnwalicki/RaspPi-Pico-Examples-Fedora#3]
At least under Fedora 37, at https://github.com/johnwalicki/RaspPi-Pico-Examples-Fedora#bonus---picotool

`sudo dnf install libusb-devel libusb`

should read

`sudo dnf install libusb1-devel libusb1`

**Comment by johnwalicki** [comment]
@adam-burns - Thanks for the report. The RPM packaging has changed.   I've submitted / merged a PR to fix my documentation.

**Comment by adam-burns** [comment]
you're welcome. note that the sdk setup under Fedora *may* also require libusb0.1 compatibility shim 

`libusb-compat-0.1`

untested on my install, as all packages were already installed.

**Comment by johnwalicki** [comment]
@adam-burns  Yeah - I wrote a long reply about `libusb-compat-0.1` and tested the compile with and without it.  Decided that it wasn't required so I deleted my comment before submitting.
